### ISSUE TITLE
hosting nodejs

### ISSUE THREAD

**Issue by danielrohers** [techparty/techparty-data#1]

**Comment by danielrohers** [comment]
https://www.openshift.com/

**Comment by fernandoporazzi** [comment]
It is important to notice that we can host just 3 applications. So we must chose carefully wich one we are going to host there. But anyway, OpenShift is a grate choice!

Let's go ahead!

**Comment by fernandoporazzi** [comment]
What about C9? https://c9.io/

**Comment by danielrohers** [comment]
C9 is a development environment, not a hosting ...
_"Your development environment, in the cloud"_

**Comment by fernandoporazzi** [comment]
Humm, I thought it could be used as a hosting platform. Sorry, my mistake ;)

**Comment by rodrigogs** [comment]
https://github.com/nodejs/node-v0.x-archive/wiki/Node-Hosting

Time to dig.

**Comment by rodrigogs** [comment]
https://github.com/nodejs/node/wiki/Node-Hosting

Updated version.

**Comment by rodrigogs** [comment]
http://bluemix.net/

Think I found it:
![sem titulo](https://cloud.githubusercontent.com/assets/2362425/11341484/c3ca79ea-91e9-11e5-824b-cc9bb7b73980.png)
